[build]
publish = "build"
command = "yarn build"


[[redirects]]
  from = "/sponsors/*"
  to = "https://sponsors.gitnation.org/jsnationlive/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/feedback"
  to = "https://www.surveymonkey.com/r/jsnation-live"

